apiVersion: apps/v1
kind: Deployment
metadata:
  name: medina-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medina
  template:
    metadata:
      labels:
        app: medina
    spec:
      containers:
      - name: medina-container
        image: medina-site
        imagePullPolicy: Never  # Important pour utiliser l'image locale
        ports:
        - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: medina-service
spec:
  type: NodePort
  selector:
    app: medina
  ports:
    - port: 81
      targetPort: 81
      nodePort: 30081  # Port externe fixe (optionnel)
