apiVersion: apps/v1
kind: Deployment
metadata:
  name: medina-website
  labels:
    app: medina
    env: production
    owner: omar.elhedfi  # Identification du propriétaire
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: medina
  template:
    metadata:
      labels:
        app: medina
        version: "${NEW_VERSION}"  # Variable Jenkins automatique
      annotations:
        build.timestamp: "$(date +%s)"  # Timestamp du déploiement
    spec:
      containers:
      - name: medina-container
        image: omarelhedfi/medina-site:${NEW_VERSION}  # Utilise la version du pipeline
        imagePullPolicy: Always  # Changez en 'Never' pour Minikube en développement
        ports:
        - containerPort: 81
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 81
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 81
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: APP_VERSION
          value: "${NEW_VERSION}"
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: medina-service
  labels:
    app: medina
    service-type: frontend
spec:
  type: NodePort
  selector:
    app: medina
  ports:
  - name: http
    port: 81
    targetPort: 81
    nodePort: 30081
    protocol: TCP
  sessionAffinity: None
